[build]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
